### ISSUE TITLE
More details needed for smoke test

### ISSUE THREAD

**Issue by lcmeng** [cap-lab/S3NAS#2]
Hi all,

Thanks for searching the work. I'm using a single GPU box to smoke test the repo. But I don't think it's working despite the required changed in the instructions. Please let me know if I'm missing something.

Command:
`bash ./base_experiment_scripts/search_backup_train.sh`
All the output I got:
```
We don't use warmup lr when using NASModelMaker
Setting drop_connect_rate as 0. We don't use drop_connect when search
train steps :  10008
next eval point :  12510
We don't use warmup lr when using NASModelMaker
Setting drop_connect_rate as 0. We don't use drop_connect when search
train steps :  12510
next eval point :  12510
We don't care about latency when we train
train steps :  150120
next eval point :  50040
We don't care about latency when we train
train steps :  437850
next eval point :  6255
```

Changes made to base_experiment_scripts/search_backup_train.sh
```
export DATA_DIR= a local directory with train-xxxxxx-of-01024 TF records
export MODEL_NAME=mixconv_super_3_4_7_4_11.json
export TEST_SAVE_FOLDER= a local directory 
export TPU_SETTINGS=""
export TARGET_LATENCY=1.40
```
Removed gsutil from all cp operations, such as
`cp ${SEARCH_LOG_FILE} ${SEARCH_DIR}/${SEARCH_LOG_FILE}`

Changes made to run/main.py
The `use_tpu` flag set to `False`
```
flags.DEFINE_bool(
    'use_tpu', default=False,
    help=('Use TPU to execute the model for training and evaluation. If'
          ' --use_tpu=false, will use whatever devices are available to'
          ' TensorFlow by default (e.g. CPU and GPU)'))
```

**Comment by thnkinbtfly** [comment]
Hi @lcmeng , 
Thanks for the smoke test!!


Sorry for the lack of information.

When I use GPU, I try to use
export TPU_SETTINGS="--use_tpu=False --transpose_input=False --use_cache=False"
* transpose_input=False : This FLAG is for optimizing input format when using TPU, not GPU.
* use_cache=False : Not necessary, but this reduces memory consumption.

Also, please check the batch size.


Additional notes
* check the MODEL_NAME. I made an env variable named MODEL_JSON, which appends '.json'. Maybe you are using path like mixconv_super_3_4_7_4_11.json.json ...
* Did you change the Latency Folder name (constraint_lut_folder FLAG) correctly?

Again, thanks. I will add details to the README file.

**Comment by thnkinbtfly** [comment]
Please open again when more information is needed.
